[build]
  functions = "netlify/functions"
  publish = "src"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

#plugins
[[plugins]]
package = "netlify-plugin-inline-functions-env"